spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinema?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 271024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    time-zone: Asia/Bangkok
    mapper:
      accept-case-insensitive-enums: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tutaiban27@gmail.com
    password: hcbkiewyrieiceva
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
            checkserveridentity: false

server:
  port: 8080

  public-url: http://localhost:8080 

cache:
  type: redis
data:
  redis:
    host: localhost
    port: 6379

vnpay:
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: ${VNPAY_RETURN_URL:http://192.168.1.30:8080/api/vnpay/vnpay-return}
  notifyUrl: ${VNPAY_NOTIFY_URL:http://localhost:8080/bookings}
  tmnCode: ${VNPAY_TMN_CODE:RNYTKXZE}
  hashSecret: ${VNPAY_HASH_SECRET:N73FR995R1V2RAFLEHNQCD2ALUOWP1RT}
  version: 2.1.0
  command: pay
  orderType: other

momo:
  # Bộ key test chuẩn khớp nhau
  partnerCode: MOMO
  accessKey: F8BBA842ECF85
  secretKey: K951B6PE1waDMi640xX08PD3vg6EkVlz
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  returnUrl: ${MOMO_RETURN_URL:rapchieuphim://checkout}
  notifyUrl: ${MOMO_NOTIFY_URL:http://localhost:8080/bookings}

jwt:
  secret: 93afe47f383323cbbb029ae356f92727
  expires-in: 2592000
